name: New Notion Articles Tracker

on:
  schedule: 
    - cron: "0 9 * * *" # every day at 9am UTC
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          echo "Starting Notion Tracker script..."
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "Notion Tracker run completed."

      - name: Restore and update known pages cache
        id: cache-known
        uses: actions/cache@v4
        with:
          path: notion_tracker_data/known_pages.json
          key: known-pages-cache
          restore-keys: |
            known-pages-

      - name: Run Notion Tracker
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          ROOT_PAGE_ID: ${{ secrets.ROOT_PAGE_ID }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          mkdir -p notion_tracker_data
          python notion_tracker_slack.py

      - name: Save known pages and update cache
        if: always()
        uses: actions/cache@v4
        with:
         path: notion_tracker_data/known_pages.json
         key: known-pages-cache
